[build]
target = "riscv32imc-esp-espidf"

[unstable]
build-std = ["std", "panic_abort"]

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = ["--cfg", "espidf_time64"]

[env]
MCU = "esp32c3"
ESP_IDF_VERSION = "v5.1.2"
